services:

  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
       - "5341:80"
    environment:
       - ACCEPT_EULA=Y
       - SEQ_FIRSTRUN_ADMINPASSWORD=Coti@2026
    networks:
       - seq-network
    volumes:
       - seq-data:/data

volumes:
  seq-data:
  
networks:
   seq-network:
       driver: bridge